import ProjectPage from '../page'

export const dynamicParams = false

export async function generateStaticParams() {
  // Preserve only the legacy /app/project/_ shell. Real project links use
  // /app/project?id=UUID; unknown path segments are not generated by export.
  return [{ id: '_' }]
}

export default function LegacyProjectPage() {
  return <ProjectPage />
}
