import LabelPage from '../page'

export const dynamicParams = false

export async function generateStaticParams() {
  // Preserve only the legacy /app/label/_ shell. Real label links use
  // /app/label?id=UUID; unknown path segments are not generated by export.
  return [{ id: '_' }]
}

export default function LegacyLabelPage() {
  return <LabelPage />
}
